services:
  angular:
    build:
      context: ./src/frontend/
    volumes:
      - ./src/frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./src/frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run watch"
    depends_on:
      - nginx
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src/frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./src/frontend/dist/front-template/browser:/usr/share/nginx/html
networks:
  app-network:
    driver: bridge