services:
  frontend:
    build:
      context: ./builds/frontend/
    command: bash
    working_dir: /app
    volumes:
      - ./src:/app
  nestjs:
    build:
      context: ./builds/nestjs/
    command: bash
    working_dir: /app
    volumes:
      - ./src:/app
  dotnet:
    build:
      context: ./src/dotnet/DotnetTemplate/
    command: bash
    working_dir: /app
    volumes:
      - ./src:/app


